<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>62885bff-bc6b-4686-9b9f-e40b20f5eb1b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\NewFolder1\**" />
    <Content Remove="Views\NewFolder1\**" />
    <EmbeddedResource Remove="Views\NewFolder1\**" />
    <None Remove="Views\NewFolder1\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\productos\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.18.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.31" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.31" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
